# Accessing array

In [2]:
import numpy as np
n1=np.array([2,4,6,7,8,9,2,3])
print(n1[0])
print(n1[-1])
print("printing all the values in array : ")
for i in n1:
    print(i)

2
3
printing all the values in array : 
2
4
6
7
8
9
2
3


In [3]:
n2=np.array([[1,2,4,5],[2,6,9,7]])
print(n2[0,1])
print(n2[1,2])
print(n2[-1,1])
print(n2[-1,:])
print(n2[:,0])

2
9
6
[2 6 9 7]
[1 2]


In [4]:
n3=np.ones([2,3,3],dtype='int32')
print(n3)
n3[0,2,2]=49
print(n3)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
[[[ 1  1  1]
  [ 1  1  1]
  [ 1  1 49]]

 [[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]]


# Size and Shape

In [5]:
print(n3.ndim)
print(n3.shape)
print(n3.size)
print(n3.dtype)
print(n3.itemsize)
print(n3.nbytes)

3
(2, 3, 3)
18
int32
4
72


# Sorting

In [6]:
n4=np.array([2,8,1,4,6,5,7,3])
print(np.sort(n4))
print(n4)

[1 2 3 4 5 6 7 8]
[2 8 1 4 6 5 7 3]


In [7]:
n5=np.array([[2,8,1],[4,6,5]])
print(np.sort(n5))
print(n5)
np.sort(n5)

[[1 2 8]
 [4 5 6]]
[[2 8 1]
 [4 6 5]]


array([[1, 2, 8],
       [4, 5, 6]])

In [8]:
#sorting colomn wise sorting axis=0 and rowwise sorting axis=1
np.sort(n5,axis=0)

array([[2, 6, 1],
       [4, 8, 5]])

In [9]:
np.sort(n5,axis=1)

array([[1, 2, 8],
       [4, 5, 6]])

# Reshaping Array and conversion

In [11]:
n6=n4.reshape(2,4)
print(n6)
n98=n4.reshape(1,-1)
n99=n4.reshape(-1,1)
print(n98)
print(n99)

[[2 8 1 4]
 [6 5 7 3]]
[[2 8 1 4 6 5 7 3]]
[[2]
 [8]
 [1]
 [4]
 [6]
 [5]
 [7]
 [3]]


In [44]:
#joining 2 arrays
n7=np.arange(1,5)
print(n7)
n8=np.arange(5,9)
print(n8)
n9=np.concatenate((n7,n8))
print(n9)

[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8]


In [51]:
#converting 1d array into 2d array
n10=np.arange(1,10)
print(n10)
n11=n10[np.newaxis,:8]
print(n11)
print(n11.shape)
n12=n10[1:,np.newaxis]
print(n12)
print(n12.shape)

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8]]
(1, 8)
[[2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(8, 1)


In [53]:
n13=np.expand_dims(n10,axis=1)
print(n13)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [54]:
n13=np.expand_dims(n10,axis=0)
print(n13)

[[1 2 3 4 5 6 7 8 9]]
