In [5]:
import numpy as np
#creating 1d array
n1=np.array([2,4,6,7,8,9,2,3])
print(n1)

[2 4 6 7 8 9 2 3]


In [7]:
#creating 2d array
n2=np.array([[1,2,4,5],[2,6,9,7]])
print(n2)

[[1 2 4 5]
 [2 6 9 7]]


In [12]:
#creating 3d array filled with zeros
n3=np.zeros([3,3])
print(n3)
n4=np.zeros([3,3],dtype='int32')
print(n4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
#creating two 3d array filled with ones

n5=np.ones([2,3,3],dtype='int32')
print(n5)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [15]:
#creating empty array filled with random junk values
n6=np.empty([1,3],dtype='int32')
print(n6)

[[460714096       606         0]]


In [17]:
#creating an array filled with range of values
n7=np.arange(10)
print(n7)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
#linearly spaced array
n8=np.linspace(0,25,12,dtype='int32')
print(n8)

[ 0  2  4  6  9 11 13 15 18 20 22 25]


In [23]:
#creating an array filled with specific values
n9=np.full([3,3],49)
print(n9)

[[49 49 49]
 [49 49 49]
 [49 49 49]]


In [25]:
#filled with specific value for an empty array
n5.fill(5)
print(n5)

[[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]]
