# Indexing and Slicing

In [4]:
import numpy as np
n1=np.arange(10)
print(n1)
print(n1[n1<5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [5]:
print(n1[(n1<3) & (n1>0)])

[1 2]


In [9]:
flag=n1>5
print(flag)
print(n1[flag])


[False False False False False False  True  True  True  True]
[6 7 8 9]


In [14]:
n1[7]=49
print(np.nonzero(n1>5))

(array([6, 7, 8, 9], dtype=int64),)


In [15]:
n1[3:8]

array([ 3,  4,  5,  6, 49])

# Stack and Split

In [19]:
n2=np.array([[1,2,3],[4,5,6]])
n3=np.array([[2,4,6],[8,7,9]])
#horizontal stack
print(np.hstack((n2,n3)))
#vertical stack
print(np.vstack((n2,n3)))

print(np.hstack((n2,n3)).shape)
print(np.vstack((n2,n3)).shape)

[[1 2 3 2 4 6]
 [4 5 6 8 7 9]]
[[1 2 3]
 [4 5 6]
 [2 4 6]
 [8 7 9]]
(2, 6)
(4, 3)


In [29]:
n4=np.arange(21)
print(n4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [30]:
np.hsplit(n4,3)
np.vsplit(n2,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

# Copy

In [31]:
#its a shallow copy just reference copied but actual array not copied
n5=n4
print(n4)
print(n5)
n5[10]=99

print(n4)
print(n5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 99 11 12 13 14 15 16 17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 99 11 12 13 14 15 16 17 18 19 20]


In [33]:
#deep copy
n6=n5.copy()
print(n6)
n6[0]=9878
print(n5)
print(n6)



[ 0  1  2  3  4  5  6  7  8  9 99 11 12 13 14 15 16 17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 99 11 12 13 14 15 16 17 18 19 20]
[9878    1    2    3    4    5    6    7    8    9   99   11   12   13
   14   15   16   17   18   19   20]


In [34]:
#This is also a shallow copy
n7=n6[:]
print(n7)

[9878    1    2    3    4    5    6    7    8    9   99   11   12   13
   14   15   16   17   18   19   20]


In [35]:
n7[0]=0
print(n7)
print(n6)

[ 0  1  2  3  4  5  6  7  8  9 99 11 12 13 14 15 16 17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 99 11 12 13 14 15 16 17 18 19 20]


# Math

In [36]:
print(n2)
print(n3)

[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [8 7 9]]


In [37]:
print(n2+n3)

[[ 3  6  9]
 [12 12 15]]


In [38]:
print(n2*n3)

[[ 2  8 18]
 [32 35 54]]


In [39]:
print(n2-n3)

[[-1 -2 -3]
 [-4 -2 -3]]


In [40]:
print(n2/n3)

[[0.5        0.5        0.5       ]
 [0.5        0.71428571 0.66666667]]


In [41]:
print(n2*n2)

[[ 1  4  9]
 [16 25 36]]


In [43]:
print(n2.sum())
print(n2.max())
print(n2.min())

21
6
1


In [55]:
#find cosine values for below array
n8=[0,30,45,60,90]
print(np.sin(n8))
print(np.cos(n8))
print(np.tan(n8))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


# Random

In [46]:
n9=np.random.rand(3,3)
print(n9)

[[0.53105847 0.78496547 0.06772027]
 [0.90609927 0.58184865 0.99747208]
 [0.92372991 0.69326671 0.63626358]]


In [50]:
n10=np.random.randint(20,size=(3,3)) # 20 is a range
print(n10)

[[ 2  2  0]
 [19  3  3]
 [12  9 18]]
